name: TimeMate
description: >
  A beautiful Flutter app to plan and organize college timetables,
  featuring multiple class inputs, grouping by day, animations, and more.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  lottie: ^2.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/timemate.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/timemate.png"
