name: TimeMate
description: >
  A beautiful Flutter app to plan and organize college timetables,
  featuring multiple class inputs, grouping by day, animations, and more.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  pdf: ^3.10.7
  printing: ^5.11.1
  excel: ^2.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.5
  animated_text_kit: ^4.2.2
  animated_background: ^2.0.0
  flutter_animate: ^4.0.0
  lottie: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/timemate.png
    - assets/animations/login.json
    - assets/animations/resetpass.json
    - assets/animations/sun.json
    - assets/animations/afternoon.json
    - assets/animations/night.json
    - assets/animations/no_class.json
    - assets/animations/empty.json
    - assets/year_tile.jpg
    - assets/animations/profile.json
    - assets/animations/settingsicon.json
    - assets/profile.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/timemate.png"
